service: boleto-check

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  boleto:
    handler: handler.boleto
    events:
      - httpApi:
          method: get
          path: /boleto/{boletoDigits}
  boleto-48:
    handler: handler.boleto48
    events:
      - httpApi:
          method: get
          path: /boleto-48/{boletoDigits}
  boleto-47:
    handler: handler.boleto47
    events:
      - httpApi:
          method: get
          path: /boleto-47/{boletoDigits}

plugins:
  - serverless-plugin-typescript
  - serverless-offline
