service: boleto-check

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1

functions:
  boleto:
    handler: handler.boleto
    events:
      - httpApi:
          method: get
          path: /boleto/{boletoDigits}
  boleto-convenio:
    handler: handler.boletoConvenio
    events:
      - httpApi:
          method: get
          path: /boleto-convenio/{boletoDigits}
  boleto-titulo:
    handler: handler.boletoTitulo
    events:
      - httpApi:
          method: get
          path: /boleto-titulo/{boletoDigits}
  boleto-generator:
    handler: handler.boletoGenerator
    events:
      - httpApi:
          method: post
          path: /boleto

plugins:
  - serverless-plugin-typescript
  - serverless-offline
